### ISSUE TITLE
M1/M2/M3 Install workarounds - AKA Protobug python doesn't work (Oct 2024)

### ISSUE THREAD

**Issue by thekoma** [GoogleCloudPlatform/genai-for-marketing#133]
Instruction to run Terraform on M1

As today protobuf python seems not enthusiast of working on M1/2/3.
To solve this problem you can "pre-create" the venv with rosetta:
```bash
# after the git clone create the venv
cd infra/scripts
arch -x86_64 /usr/bin/python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```

Terraform template library does not exist for M1 (we should actually migrate from it as is not developed anymore).
```bash
# init will fail. Do not panic
terraform init
brew install kreuzwerker/taps/m1-terraform-provider-helper
m1-terraform-provider-helper activate
m1-terraform-provider-helper install hashicorp/template -v v2.2.0
m1-terraform-provider-helper lockfile upgrade
terraform init
```

**Comment by chmstimoteo** [comment]
Fixed this issue by providing your guidance in the installation documentation: https://github.com/GoogleCloudPlatform/genai-for-marketing/blob/main/infra/README.md#step-1---terraform-deployment
