### ISSUE TITLE
README section on "Create a Generative AI Agent" unclear, seems to include an impossible step

### ISSUE THREAD

**Issue by mikrovvelle** [GoogleCloudPlatform/genai-for-marketing#27]
Following the deployment steps described in the README.md, this refers to a [Codelab](https://codelabs.developers.google.com/codelabs/dialogflow-generator#0), which walks through how to set up a Gen AI Agent. One of the steps is either unclear, or actually impossible:

The README's second bullet point (referring to the Codelab) states:
> - In step 3 of this Codelab you can provide a different URL to be indexed by the Generative AI Agent, for example `support.google.com/google-ads/*`.

However, since this is building a Chat agent, one would need to verify the domain at `support.google.com`, which requires editing/write privileges to that domain, which no mortal has.

The original Codelab provides a Cloud Storage link to some documentation for the Red Cross, but using that as a data store doesn't make sense for a marketing demo.

The README should specify a feasible way to use Google Ads documentation as a data store, such as providing a GCS link for unstructured documents.

**Comment by leiterenato** [comment]
Hi @mikrovvelle 
Yes, you are right, you won't have access to this DNS to verify that domain.

You can create a datastore with a simple PDF, just for testing.
Here is another Codelab with some sample PDFs: https://codelabs.developers.google.com/codelabs/how-to-query-vertex-ai-search-cloud-run-service#0

**Comment by mikrovvelle** [comment]
Thanks for the comment, but why was the issue closed without a fix?

The README instructions show no update in the last 3 months. Or has a fix been checked into another branch?

**Comment by leiterenato** [comment]
Yes, there is a new version under the branch v2.0.
I will work to update the readme accordingly.
