### ISSUE TITLE
Unable to deploy application

### ISSUE THREAD

**Issue by erodneyCorus** [GoogleCloudPlatform/genai-for-marketing#3]
I can't seem to deploy the application on my GCP instance.  Which permissions do I need in my service account?  

Thanks.

**Comment by leiterenato** [comment]
Hi @erodneyCorus,
The permissions below would be enough to use the application:
```
BigQuery Data Viewer
BigQuery Job User
Container Registry Service Agent
Data Catalog TagTemplate User
Discovery Engine Viewer
GenApp Content creation SA custom
Logs Writer
Storage Object Creator
```

You still need the following permissions to deploy the app:
```
App Engine Admin
App Engine flexible environment Service Agent
Artifact Registry Administrator
```

Alternatively you can deploy to Cloud Run, if that is easier to you.
Just build the container, push to Container Registry and deploy to run.

**Comment by leiterenato** [comment]
Can you elaborate on what errors are you facing?

**Comment by leiterenato** [comment]
I am closing this issue for now. Please let me know if you need any assistance.

**Comment by erodneyCorus** [comment]
Thanks Renato!  I was able to deploy but are still having some issues with the site (it doesn’t render).  Will take another look when I have a chance.
