### ISSUE TITLE
Backend API deployment failure

### ISSUE THREAD

**Issue by louisphilip** [GoogleCloudPlatform/genai-for-marketing#37]
![cloud run deployment fail](https://github.com/GoogleCloudPlatform/genai-for-marketing/assets/72431908/a429a042-481c-4942-a882-f76ea26555ef)
Cannot seem to build the backend API and found that it cannot find the files with the path /code/app/config.toml. 

![file not found error](https://github.com/GoogleCloudPlatform/genai-for-marketing/assets/72431908/96d7c754-4b1b-44ad-a82d-c7f8845f94a2)

Has anybody come across this before?

**Comment by evangeliasoultani** [comment]
You would need to correct the path. You can replace it to /app/config.toml and it should work.

**Comment by leiterenato** [comment]
Hi @louisphilip @evangeliasoultani 
I updated the path and now it is working fine. Please pull the latest code.
I also updated the README file with some important steps to deploy the sample code.
Please let me know if they are clear to follow.

Feel free to reopen the case if your still have issues to deploy.
Thank you
