### ISSUE TITLE
Backend deploy failure

### ISSUE THREAD

**Issue by DanieleGargini-Intarget** [GoogleCloudPlatform/genai-for-marketing#38]
when I try to deploy the backend I get this error

```
2024-04-15 09:34:22.067 CEST
  File "/app/main.py", line 197, in <module>
2024-04-15 09:34:22.068 CEST
    path="/marketing", app=StaticFiles(directory="/static", html=True), name="static"
2024-04-15 09:34:22.069 CEST
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-15 09:34:22.069 CEST
  File "/usr/local/lib/python3.11/site-packages/starlette/staticfiles.py", line 59, in __init__
2024-04-15 09:34:22.072 CEST
    raise RuntimeError(f"Directory '{directory}' does not exist")
2024-04-15 09:34:23.075 CEST
RuntimeError: Directory '/static' does not exist
```

even if I create the folder _static_ I get the same error

does anyone run into the same problem?

**Comment by evangeliasoultani** [comment]
Same issue. Also the path marketing does not seem to be valid. If you comment this block, the deployment will work, however I am not sure how critical is for the solution.

**Comment by leiterenato** [comment]
@DanieleGargini-Intarget @evangeliasoultani 
I updated the main.py and removed this part. In the first version of the code we were using a static folder inside of the container to serve the HTML/CSS/JS files and now this is not necessary anymore.

Please pull the latest code and rebuild your container.
I updated the README file with some important steps to deploy the sample code.
Please let me know if they are clear to follow.
Best
