### ISSUE TITLE
Error when creating a new campaign

### ISSUE THREAD

**Issue by mdh-e-dialog** [GoogleCloudPlatform/genai-for-marketing#39]
Hi! My team was succesfull in deploying and authenticating the app.

The moment I tried to create a campaign, I have a pydantic error in the Cloud Run backend

POST
```
https://genai-marketing-gmgp25dusq-ey.a.run.app/users/3Z0Qr3xTagdTuwFNrOoII228MW72/campaigns
```
RESPONSE
```json 
{'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https://errors.pydantic.dev/2.7/v/model_attributes_type'}
```

Looking at the payload that is sent, it seems to match the CampaignCreateRequest in the pydantic schema file
```json
{
  "campaign_name":"GACon Campaign 2024",
  "theme":"Introducing a new line of men's leather shoes",
  "brief": {
    "gender_select_theme":"Men",
    "age_select_theme":"30-40",
    "objective_select_theme":"Increasing Sales",
    "competitor_select_theme":"Fashion Forward"
  }
}
```

We deployed it last week, I did not find a commit or a bug fix in this period.

Regards,
Mark

**Comment by leiterenato** [comment]
Hi @mdh-e-dialog 
Thanks for using the sample code.
I updated the code and the README file with some important steps to deploy the demo.
Could you please review them and update your container / Firebase?

Please let me know if the steps are clear to follow.
Thanks again
