### ISSUE TITLE
local variable 'tag_full_path' referenced before assignment

### ISSUE THREAD

**Issue by HelderMartinsDevOps** [GoogleCloudPlatform/genai-for-marketing#4]
Hi,

I'm getting this error when running the following step:

```
from aux_data import bq_tag_generation

bq_tag_generation.create_template_and_tag_bq(
    PROJECT_ID,
    DATASET_ID,
    TAG_TEMPLATE_ID,
    LOCATION
)
```
![image](https://github.com/GoogleCloudPlatform/genai-for-marketing/assets/43578150/5361e164-4462-405e-9bcf-e7ffa0a875e9)

**Comment by leiterenato** [comment]
Hi @HelderMartinsDevOps ,
Quick questions:

Did you changed these variables to your configuration?
```
PROJECT_ID = '<YOUR PROJECT ID>'  # Change to your project ID
LOCATION = 'us-central1'
DATASET_ID = 'cdp_dataset'

# Tag template 
TAG_TEMPLATE_ID = 'llmcdptemplate'
TAG_TEMPLATE_PATH = f"projects/{PROJECT_ID}/locations/{LOCATION}/tagTemplates/{TAG_TEMPLATE_ID}"

# Set the project id
! gcloud config set project {PROJECT_ID}
```

I tried here and everything is working.  
Please try to restart the Kernel of you notebook and try again. 

Let me know how if you manage to fix it.
Best

**Comment by leiterenato** [comment]
I will close this issue for now. Please let me know if you need any assistance.
