### ISSUE TITLE
"DataStore API is not enabled" Error.

### ISSUE THREAD

**Issue by simoneeti** [GoogleCloudPlatform/genai-for-marketing#43]
Hi, I'm trying the tf strategy to deploy to Cloud. I'm getting the next error although the API shows up as enabled in the console.
│ Error: Error creating DataStore: googleapi: Error 403: Discovery Engine
 API has not been used in project PROJECT before or it is disabled. 

│   with google_discovery_engine_data_store.search_datastore,
│   on search-conversation.tf line 20, in resource "google_discovery_engine_data_store" "search_datastore":
│   20: resource "google_discovery_engine_data_store" "search_datastore"

**Comment by leiterenato** [comment]
Sorry @simoneeti
We will need to revisit the terraform scripts. There are some minor things that are breaking it.
Please use the manual step for now.
