### ISSUE TITLE
source: not found

### ISSUE THREAD

**Issue by simoneeti** [GoogleCloudPlatform/genai-for-marketing#44]
Ubuntu 20
source works as expected through the command line.

│ Error running command 'source venv/bin/activate; python3 aux_data/Create_GDrive_folder.py
│ --folder_name="genai-marketing-assets"
│ --service_account_email="genai-marketing-run@PROJECT.iam.gserviceaccou
nt.com"':
│ exit status 1. Output: /bin/sh: 1: source: not found

**Comment by leiterenato** [comment]
Sorry @simoneeti
We will need to revisit the terraform scripts. There are some minor things that are breaking it.
Please use the manual step for now.
