### ISSUE TITLE
Request to Drive with ADC has insufficient authentication scopes.

### ISSUE THREAD

**Issue by simoneeti** [GoogleCloudPlatform/genai-for-marketing#45]
Ubuntu 20
aux_data/Create_GDrive_folder.py line 140

│ googleapiclient.errors.HttpError: <HttpError 403 when requesting
│ https://www.googleapis.com/drive/v3/files?q=name%3D%27genai-marketing-assets%27&pageSize=10&fields=nextPageToken%2C+files%28id%2C+name%29&supportsAllDrives=true&includeItemsFromAllDrives=true&alt=json
│ returned "Request had insufficient authentication scopes.". Details:
│ "[{'message': 'Insufficient Permission', 'domain': 'global', 'reason':
│ 'insufficientPermissions'}]">

**Comment by leiterenato** [comment]
Sorry @simoneeti.
We are facing some issues with the terraform script.
Please use the manual steps for now ...
