### ISSUE TITLE
Exit status 137 while running data_gen.py

### ISSUE THREAD

**Issue by simoneeti** [GoogleCloudPlatform/genai-for-marketing#47]
│ Error running command 'source venv/bin/activate; python3 -c 'from aux_data import data_gen;
│ data_gen.generate_and_populate_dataset(PROJECT_ID=PROJECT,DATASET_ID="gai_marketing",create_tables=False)'': exit status 137.
│ Output: /bin/sh: 1: source: not found
│ Killed

**Comment by leiterenato** [comment]
I fixed this error.
Please pull the new changes and try again.
