### ISSUE TITLE
I get error 「No module named 'aux_data' 」in step 6- Prepare BigQuery and Dataplex

### ISSUE THREAD

**Issue by cashwu** [GoogleCloudPlatform/genai-for-marketing#48]
I had set `PROJECT_ID` and `LOCATION` environmental variables .
when I run `python3 1_env_setup_script.py` I get error

```shell
Traceback (most recent call last):
  File "/genai-for-marketing/installation_scripts/1_env_setup_script.py", line 19, in <module>
    from aux_data import data_gen
ModuleNotFoundError: No module named 'aux_data'
```

<img width="1400" alt="image" src="https://github.com/GoogleCloudPlatform/genai-for-marketing/assets/4278751/6ed6828f-f46a-4217-86f2-2b6ef4945a25">

I don't know how to fix the error , could help me

**Comment by leiterenato** [comment]
I fixed this issue. The scripts were in a different folder.
Please pull the new changes and try again.
