### ISSUE TITLE
I don't know step「8- Add your Looker Dashboards」

### ISSUE THREAD

**Issue by cashwu** [GoogleCloudPlatform/genai-for-marketing#49]
I don't know how to set 「include links to the Looker dashboards for Marketing Insights.」?
Before the step, I need create a Looker dashboard for this ?

**Comment by leiterenato** [comment]
Hi @cashwu 
Yes, there are some pages that can render Looker Dashboards.
If you don't have any, you don't need to update this HTML file.
Just be aware that these pages will be empty and won't show any dashboard.
Best
Renato
