### ISSUE TITLE
How to find an index of demos like this?

### ISSUE THREAD

**Issue by octopop** [GoogleCloudPlatform/genai-for-marketing#54]
*Not an Issue*

Question: **Is there an index or an awesome list equivalent of demos like these**? How do we discover more? Similar to this gen-ai demo; there is a data analytics (https://github.com/GoogleCloudPlatform/data-analytics-golden-demo). These are incredibly useful for our organization.

**Comment by leiterenato** [comment]
Hi @octopop 
Thanks for using these sample codes!
We have a repository with a lot of content:
https://github.com/GoogleCloudPlatform/applied-ai-engineering-samples

I also created the Customer Experience Modernization repo:
https://github.com/GoogleCloudPlatform/customer-experience-modernization

Some other repos I created but don't support anymore:
https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline
https://github.com/GoogleCloudPlatform/t5x-on-vertex-ai
https://github.com/GoogleCloudPlatform/nvidia-merlin-on-vertex-ai
