### ISSUE TITLE
Installation script faulty?

### ISSUE THREAD

**Issue by dfalk-epro** [GoogleCloudPlatform/genai-for-marketing#58]
The [installation script ](https://github.com/GoogleCloudPlatform/genai-for-marketing/blob/38202845d27f222aef9729b970095b3e7223c9a2/installation_scripts/genai_marketing_automation.sh)described [here ](https://github.com/GoogleCloudPlatform/genai-for-marketing/blob/38202845d27f222aef9729b970095b3e7223c9a2/installation_scripts/tutorial.md) does not work properly. It refers to toml config files that do not exist. For e.g.: 

[Codeline
](https://github.com/GoogleCloudPlatform/genai-for-marketing/blob/38202845d27f222aef9729b970095b3e7223c9a2/installation_scripts/genai_marketing_automation.sh#L73)

```
# Updating the Project and Location details in app config and override files
sed -i "s|project_id = \"\"|project_id = '${PROJECT_ID}'|" genai-for-marketing/app/app_config.toml
sed -i "s|location = \"us-central1\"|location = '${LOCATION}'|" genai-for-marketing/app/app_config.toml
sed -i "s|project_id = \"\"|project_id = '${PROJECT_ID}'|" genai-for-marketing/app/override.toml
sed -i "s|location = \"us-central1\"|location = '${LOCATION}'|" genai-for-marketing/app/override.toml
```

**Comment by leiterenato** [comment]
@dfalk-epro Thanks for submitting the issue.
Yes, there is a problem with this script. We are working to update the deployment scripts.

Meanwhile, use the manual steps in the main README file or the terraform scripts under /tf.
