### ISSUE TITLE
Application references Deprecated Model - TextBison

### ISSUE THREAD

**Issue by awaemmanuel** [GoogleCloudPlatform/genai-for-marketing#72]
App references Text-Bison that's deprecated: `google.api_core.exceptions.NotFound: 404 Publisher Model `publishers/google/models/text-bison` is not found.,2024-06-30T16:20:29.748913Z`

![image](https://github.com/GoogleCloudPlatform/genai-for-marketing/assets/3170798/62ed086d-3e7e-4e1e-9d99-27966d5b78ed)

**Comment by michaelwsherman** [comment]
I wonder if just adding @002 should fix it. @ghchinoy have you seen this error before?

**Comment by ghchinoy** [comment]
I have not, though I believe this is fixed now.
